name: Create Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build-release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
        name: Dump Context
