name: Create PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number
        type: string
        default: ''
        required: true
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: create-release-version
        name: Create Release Version
        run: |
          mvn \
            compile -Dfoo=${{ github.event.inputs.version }}
          echo "${{ github.event.inputs.version }}" > version.txt
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: release/v${{ github.event.inputs.version }}
          commit-message: "Release ${{ github.event.inputs.version }}"
          title: "Release ${{ github.event.inputs.version }}"
          author: "github-actions <github-actions@github.com>"
          body: "Update `pom.xml`s and related files to release version ${{ github.event.inputs.version }}"
          delete-branch: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - id: tag-release
        name: Tag release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout release/v${{ github.event.inputs.version }}
          git tag -a v${{ github.event.inputs.version }} -m "Release Tag ${{ github.event.inputs.version }}"
          git push --tags
      - id: setup-snapshot
        name: Setup next snapshot version
        run: |
          echo "${{ github.event.inputs.version }}-SNAPSHOT" > version.txt
          git add .
          git commit -m "next snapshot version"
          git push --set-upstream origin release/v${{ github.event.inputs.version }}
