name: Create Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build-release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.title, 'Release ')
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
        name: Dump Context
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: |
          cat version.txt
