name: Create Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build-release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.title, 'Release ')
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
        name: Dump Context
      - name: Get version
        id: get_version
        run: echo '${{ github.head_ref }}' | sed 's/release\/v/::set-output name=VERSION::/'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Setup next Snapshot version
        run: |
          cat version.txt
          echo "${{ steps.get_version.outputs.VERSION }}-SNAPSHOT" > version.txt
      - name: Create Pull Request for next Snapshot
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Snapshot version"
          title: "Snapshot version"
          author: "github-actions <github-actions@github.com>"
          body: "Update all project `pom.xml` and related files to post-${{ steps.get_version.outputs.VERSION }} snapshot version"
      - uses: actions/checkout@v3
      - run: cat version.txt
#      - run: mvn
      - name: Create Release v${{ steps.get_version.outputs.VERSION }}
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          # generateReleaseNotes: true
          draft: true
          artifacts: "version.txt,pom.xml"
